language: ruby
cache: bundler
rvm:
- 2.3
install:
- bundle install --jobs=3 --deployment
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: master
  on:
    branch: source
