title: Faiz's Memory Dump
url: https://faizilham.github.io
author: Faiz Ilham
# email: faizilham.faizz@gmail.com
description: > # this means to ignore newlines until "twitter_username:"
  Snapshots of my current working memory

# social links
# twitter_username: jekyllrb
github_username: faizilham
rss: RSS
# dribbble_username: jekyll
facebook_username: faiz.ilham
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: faizilham
# pinterest_username: jekyll
# youtube_username: jekyll
# youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
# youtube_channel_name: CloudCannon
# telegram_username: jekyll
# googleplus_username: +jekyll
# microdotblog_username: jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

permalink: /:year/:month/:title

show_excerpts: false # set to true to show excerpts on the homepage

exclude:
  - script
  - README.md
  - LICENSE.txt
  - Gemfile
  - Rakefile
  - '*.gemspec'

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d"

# archive pages
jekyll-archives:
  enabled:
    - tags
    - year
    - month
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    tag: '/tag/:name/'

  layouts:
    year: year-archive
    month: month-archive
    tag: tag-archive

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up

header_pages:
- about.md

# Build settings
# theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
