title: faiz.memdump()
url: https://faizilham.github.io
author: Faiz Ilham
# email: faizilham.faizz@gmail.com
description: > # this means to ignore newlines until "twitter_username:"
  A digital snapshot of my memories

# social links
# twitter_username: jekyllrb
github_username: faizilham
rss: RSS
# dribbble_username: jekyll
facebook_username: faiz.ilham
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: faizilham
# pinterest_username: jekyll
# youtube_username: jekyll
# youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
# youtube_channel_name: CloudCannon
# telegram_username: jekyll
# googleplus_username: +jekyll
# microdotblog_username: jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

# disqus:
#   shortname: labsfaiz

permalink: /:title

show_excerpts: true # set to true to show excerpts on the homepage

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up

header_pages:
- _pages/archive.md
- _pages/lab.md
- _pages/about.md

exclude:
  - script
  - tmp
  - vendor
  - README.md
  - LICENSE.txt
  - Gemfile
  - Rakefile
  - '*.gemspec'

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d"

# collections
collections:
  pages:
    output: true
    permalink: /:path

# archive pages
jekyll-archives:
  enabled:
    - tags
    - year
  layout: archive
  permalinks:
    year: '/archive/:year/'
    tag: '/tag/:name/'

sass:
  style: compressed

kramdown:
  footnote_backlink: "↩︎︎"

# Build settings

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
